  
 ## A. `Triggers `

A **trigger** in MySQL is a special type of `stored program` that automatically executes or "fires" in response to certain events on a particular table. Triggers are useful for enforcing business rules, maintaining data integrity, auditing changes, and performing automated actions in the database without requiring additional application logic.

## Table of Contents

1. [Types of Triggers](#types-of-triggers)
2. [Creating Triggers](#creating-triggers)
3. [Trigger Syntax](#trigger-syntax)
4. [Examples](#examples)
    - [Example 1: BEFORE INSERT Trigger](#example-1-before-insert-trigger)
    - [Example 2: AFTER UPDATE Trigger](#example-2-after-update-trigger)
    - [Example 3: BEFORE DELETE Trigger](#example-3-before-delete-trigger)
5. [Managing Triggers](#managing-triggers)
6. [Best Practices](#best-practices)
7. [Limitations and Considerations](#limitations-and-considerations)
8. [Difference Between Triggers and Stored Procedures](#difference-between-triggers-and-stored-procedures)

---

## Types of Triggers

In MySQL, triggers are classified based on the timing and the event that activates them:

1. **Timing:**
   - **BEFORE:** The trigger executes before the triggering event (INSERT, UPDATE, DELETE) occurs.
   - **AFTER:** The trigger executes after the triggering event occurs.

2. **Event:**
   - **INSERT:** Fired when a new row is inserted into a table.
   - **UPDATE:** Fired when an existing row is updated.
   - **DELETE:** Fired when a row is deleted.

Combining these, you can have up to six types of triggers for each table:

- BEFORE INSERT
- AFTER INSERT
- BEFORE UPDATE
- AFTER UPDATE
- BEFORE DELETE
- AFTER DELETE

**Note:** MySQL does not support triggers for `SELECT` statements.

## Creating Triggers

To create a trigger in MySQL, you use the `CREATE TRIGGER` statement. You must specify:

- **Trigger Name:** A unique name for the trigger.
- **Timing:** BEFORE or AFTER.
- **Event:** INSERT, UPDATE, or DELETE.
- **Table:** The table to which the trigger is associated.
- **Body:** The SQL statements that define what the trigger does.

### Prerequisites

- **Privileges:** You need the `CREATE TRIGGER` privilege for the database.
- **One Trigger per Event per Timing:** MySQL allows only one trigger per combination of timing and event per table.

## Trigger Syntax

```sql
CREATE TRIGGER trigger_name
    {BEFORE | AFTER} {INSERT | UPDATE | DELETE}
    ON table_name
    FOR EACH ROW
    BEGIN
        -- Trigger logic here
    END;
```

- **trigger_name:** Name of the trigger. It must be unique within the database.
- **BEFORE | AFTER:** Specifies when the trigger should execute relative to the triggering event.
- **INSERT | UPDATE | DELETE:** The event that activates the trigger.
- **table_name:** The table the trigger is associated with.
- **FOR EACH ROW:** Indicates that the trigger will execute for each row affected by the event.
- **Trigger Logic:** The SQL statements to execute when the trigger fires. You can access the old and new values using `OLD` and `NEW` qualifiers.

### Example Structure

```sql
CREATE TRIGGER before_employee_insert
    BEFORE INSERT
    ON employees
    FOR EACH ROW
BEGIN
    -- Example logic: Ensure the salary is not negative
    IF NEW.salary < 0 THEN
        SET NEW.salary = 0;
    END IF;
END;
```

## Examples

### Example 1: BEFORE INSERT Trigger

**Scenario:** Automatically set the `created_at` timestamp before inserting a new row.

```sql
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    created_at DATETIME
);

DELIMITER $$

CREATE TRIGGER before_user_insert
    BEFORE INSERT
    ON users
    FOR EACH ROW
BEGIN
    IF NEW.created_at IS NULL THEN
        SET NEW.created_at = NOW();
    END IF;
END$$

DELIMITER ;
```

**Explanation:**

- **Trigger Name:** `before_user_insert`
- **Timing:** BEFORE INSERT
- **Table:** `users`
- **Logic:** If the `created_at` field is not provided (`NULL`), set it to the current timestamp using `NOW()`.

### Example 2: AFTER UPDATE Trigger

**Scenario:** Maintain an audit log whenever a user's information is updated.

```sql
CREATE TABLE user_audit (
    audit_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    changed_at DATETIME,
    changed_by VARCHAR(50),
    old_username VARCHAR(50),
    new_username VARCHAR(50)
);

DELIMITER $$

CREATE TRIGGER after_user_update
    AFTER UPDATE
    ON users
    FOR EACH ROW
BEGIN
    INSERT INTO user_audit (
        user_id,
        changed_at,
        changed_by,
        old_username,
        new_username
    )
    VALUES (
        OLD.id,
        NOW(),
        USER(),
        OLD.username,
        NEW.username
    );
END$$

DELIMITER ;
```

**Explanation:**

- **Trigger Name:** `after_user_update`
- **Timing:** AFTER UPDATE
- **Table:** `users`
- **Logic:** Inserts a new record into the `user_audit` table capturing the old and new `username`, the time of change, and the user who made the change.

### Example 3: BEFORE DELETE Trigger

**Scenario:** Prevent deletion of users who are marked as administrators.

```sql
DELIMITER $$

CREATE TRIGGER before_user_delete
    BEFORE DELETE
    ON users
    FOR EACH ROW
BEGIN
    IF OLD.role = 'admin' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Cannot delete an administrator.';
    END IF;
END$$

DELIMITER ;
```

**Explanation:**

- **Trigger Name:** `before_user_delete`
- **Timing:** BEFORE DELETE
- **Table:** `users`
- **Logic:** Checks if the user to be deleted has the role 'admin'. If so, it aborts the deletion and raises an error using the `SIGNAL` statement.

## Managing Triggers

### Viewing Existing Triggers

To list all triggers in the current database:

```sql
SHOW TRIGGERS;
```

This command displays information such as the trigger name, associated table, event, timing, and the trigger's body.

### Dropping a Trigger

To remove a trigger, use the `DROP TRIGGER` statement:

```sql
DROP TRIGGER [IF EXISTS] trigger_name;
```

**Example:**

```sql
DROP TRIGGER IF EXISTS before_user_insert;
```

**Note:** Dropping a trigger requires the `DROP` privilege for triggers on the table.

## Best Practices

1. **Use Triggers Sparingly:** While triggers are powerful, overusing them can make the database logic complex and harder to maintain. Consider if application-level logic could achieve the same result more transparently.

2. **Keep Trigger Logic Simple:** Complex logic can lead to performance issues and make debugging difficult. Aim for clarity and simplicity.

3. **Document Triggers:** Clearly document the purpose and behavior of each trigger to aid future maintenance and understanding.

4. **Avoid Side Effects:** Triggers should not perform actions that lead to unexpected side effects, such as modifying unrelated tables excessively or causing recursive trigger calls.

5. **Handle Exceptions Gracefully:** Use proper error handling within triggers to prevent unwanted disruptions during data operations.

6. **Test Thoroughly:** Ensure triggers behave as expected under various scenarios to avoid data inconsistencies.

## Limitations and Considerations

1. **One Trigger per Event per Timing per Table:** MySQL allows only one trigger for each combination of timing (BEFORE/AFTER) and event (INSERT/UPDATE/DELETE) per table. To perform multiple actions for the same event, combine them within a single trigger.

2. **No Native Support for INSTEAD OF Triggers:** Unlike some other database systems (e.g., SQL Server), MySQL does not support `INSTEAD OF` triggers.

3. **Performance Impact:** Triggers add overhead to data modification operations. Excessive or inefficient triggers can degrade performance.

4. **Recursion and Nested Triggers:** MySQL does not support recursive triggers, meaning a trigger cannot directly or indirectly cause itself to execute again.

5. **Limited Transaction Control:** Triggers execute within the transaction of the triggering statement. You cannot commit or roll back transactions within a trigger.

6. **Error Handling:** If a trigger encounters an error, it can cause the entire operation (e.g., INSERT, UPDATE, DELETE) to fail. Proper error handling is essential to avoid unintended data issues.

7. **Access to OLD and NEW:** 
   - **INSERT Triggers:** Only `NEW` is available.
   - **DELETE Triggers:** Only `OLD` is available.
   - **UPDATE Triggers:** Both `OLD` and `NEW` are available.

## Difference Between Triggers and Stored Procedures

While both triggers and stored procedures are types of stored programs in MySQL, they serve different purposes and have distinct behaviors:

- **Invocation:**
  - **Triggers:** Automatically execute in response to specific table events (INSERT, UPDATE, DELETE).
  - **Stored Procedures:** Manually invoked by the user or application via the `CALL` statement.

- **Usage:**
  - **Triggers:** Used for automatic enforcement of rules, auditing, and maintaining data integrity.
  - **Stored Procedures:** Used to encapsulate reusable logic, perform complex operations, and support modular programming.

- **Parameters:**
  - **Triggers:** Do not accept parameters; they operate based on the triggering event's context.
  - **Stored Procedures:** Can accept input, output, and input/output parameters.

- **Control Flow:**
  - **Triggers:** Execute as part of the transaction that triggered them.
  - **Stored Procedures:** Execute independently, though they can be part of transactions initiated by the caller.

Understanding when to use triggers versus stored procedures is crucial for designing efficient and maintainable database systems.

---

## Conclusion

Triggers in MySQL are powerful tools for automating database operations and enforcing business rules at the database level. They can help maintain data integrity, perform auditing, and automate repetitive tasks without requiring changes to application code. However, it's essential to use them judiciously, keeping their logic as simple as possible, to avoid complexity and potential performance issues. Proper documentation and adherence to best practices will ensure that triggers contribute positively to your database design and application functionality.

## B. `OLD` and `NEW` keywords

In SQL triggers, the `OLD` and `NEW` keywords are used to reference the values of a row before and after a triggering event.

- **`OLD`**: Refers to the value of a column before an `UPDATE` or `DELETE` operation.
- **`NEW`**: Refers to the value of a column after an `INSERT` or `UPDATE` operation.

### When to use `OLD`:
- Use `OLD` to refer to the values that existed before the update or delete operation.
- It is primarily used in `AFTER UPDATE`, `BEFORE UPDATE`, and `BEFORE DELETE` triggers.

### When to use `NEW`:
- Use `NEW` to refer to the values that are being inserted or updated after the triggering event.
- It is used in `AFTER INSERT`, `BEFORE INSERT`, and `AFTER UPDATE` triggers.

### In your trigger example:

Since you're logging the old and new usernames when a user record is updated:

- **`OLD.username`**: Refers to the username before it was updated.
- **`NEW.username`**: Refers to the username after it was updated.

Thus, for an `AFTER UPDATE` trigger:
- **Use `OLD`** to capture the previous value of the username.
- **Use `NEW`** to capture the new value after the update has occurred.

This logic ensures that the audit log captures the username change history by storing both the old and new usernames.

### Trigger Summary:
- **`OLD.id`**: References the user’s ID before the update.
- **`NEW.username`**: References the new username after the update.
- **`OLD.username`**: Captures the old username before the update.

In your `user_audit` trigger, this is used correctly to track changes to usernames.

 `OLD` and `NEW` are part of the SQL trigger **syntax**. They are special keywords used in triggers to refer to the values of the row before and after a modification.

Here’s how they work in terms of syntax:

- **`OLD`**: Refers to the existing values of a row before an `UPDATE` or `DELETE` operation. It is valid only in `UPDATE` and `DELETE` triggers.
  
- **`NEW`**: Refers to the new values that will be applied to a row during an `INSERT` or `UPDATE` operation. It is valid in `INSERT` and `UPDATE` triggers.

### Where `OLD` and `NEW` are part of the syntax:

1. **`AFTER UPDATE` or `BEFORE UPDATE` Triggers**:
   - Both `OLD` and `NEW` can be used to reference values before and after the update.
   
2. **`AFTER DELETE` or `BEFORE DELETE` Triggers**:
   - Only `OLD` is available, as the row is being deleted and there are no "new" values.

3. **`AFTER INSERT` or `BEFORE INSERT` Triggers**:
   - Only `NEW` is available, as there are no "old" values for a new row.

### Example of Syntax with `OLD` and `NEW`:

#### 1. **Update Trigger** (using both `OLD` and `NEW`):
```sql
CREATE TRIGGER after_user_update
AFTER UPDATE ON users
FOR EACH ROW
BEGIN
    INSERT INTO user_audit (user_id, old_username, new_username)
    VALUES (OLD.id, OLD.username, NEW.username);  -- `OLD` and `NEW` are part of syntax here
END;
```

#### 2. **Delete Trigger** (only using `OLD`):
```sql
CREATE TRIGGER after_user_delete
AFTER DELETE ON users
FOR EACH ROW
BEGIN
    INSERT INTO user_audit (user_id, old_username)
    VALUES (OLD.id, OLD.username);  -- only `OLD` is available
END;
```

#### 3. **Insert Trigger** (only using `NEW`):
```sql
CREATE TRIGGER after_user_insert
AFTER INSERT ON users
FOR EACH ROW
BEGIN
    INSERT INTO user_audit (user_id, new_username)
    VALUES (NEW.id, NEW.username);  -- only `NEW` is available
END;
```

### Conclusion:
`OLD` and `NEW` are **mandatory** syntax elements when you need to refer to the old or new values of a row in a trigger. They are part of how SQL triggers handle row-level operations and cannot be changed. If you don't need to refer to row values, you can omit them, but when row data is involved, `OLD` and `NEW` are essential syntax elements.

## C. `BEFORE` and `AFTER` triggers 

In MySQL, `BEFORE` and `AFTER` triggers are used to define actions that occur automatically in response to `INSERT`, `UPDATE`, or `DELETE` events on a table. The difference between `BEFORE` and `AFTER` lies in when the trigger executes relative to the event:

### 1. **BEFORE Triggers**:
- **Execution Timing**: `BEFORE` triggers are executed before the specified event (`INSERT`, `UPDATE`, or `DELETE`) happens.
- **Use Case**: Use `BEFORE` triggers when you need to validate or modify the data before the event occurs.
  
   Common scenarios:
   - **Validating data**: Ensure the data is in the correct format or meets certain conditions before it is inserted or updated.
   - **Setting default values**: Automatically adjust or set certain field values before insertion or updating.
   - **Preventing an operation**: You can signal an error (using `SIGNAL`) if certain conditions aren't met, effectively preventing the event.

   Example of a `BEFORE INSERT` trigger:
   ```sql
   CREATE TRIGGER before_insert_users
   BEFORE INSERT ON users
   FOR EACH ROW
   BEGIN
     IF NEW.username IS NULL THEN
       SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Username cannot be null';
     END IF;
   END;
   ```

### 2. **AFTER Triggers**:
- **Execution Timing**: `AFTER` triggers are executed after the specified event (`INSERT`, `UPDATE`, or `DELETE`) has occurred.
- **Use Case**: Use `AFTER` triggers when you need to perform actions based on the result of the event.
  
   Common scenarios:
   - **Logging changes**: You can use `AFTER` triggers to log changes to another table (such as keeping an audit trail of operations).
   - **Cascading actions**: Perform additional actions that depend on the completion of the insert, update, or delete (e.g., updating another table or sending a notification).
   - **Enforcing integrity**: Apply changes to other tables after an operation is successfully completed.

   Example of an `AFTER INSERT` trigger:
   ```sql
   CREATE TRIGGER after_insert_users
   AFTER INSERT ON users
   FOR EACH ROW
   BEGIN
     INSERT INTO user_logs (user_id, action, timestamp)
     VALUES (NEW.id, 'INSERT', NOW());
   END;
   ```

### Summary of When to Use:

- **BEFORE Triggers**: 
  - Modify or validate the data **before** it is inserted, updated, or deleted.
  - Prevent the event by signaling an error if needed.
  
- **AFTER Triggers**: 
  - Perform actions **after** the event has occurred.
  - Useful for logging, sending notifications, or making related changes after the main event.

In both cases, triggers can be useful for maintaining data integrity, automating repetitive tasks, or enforcing business rules.

## D. Examples


### 1. Triggers That Audit Data.


  **--After Insert triggers--**
 ```sql
use triggers_database;
drop trigger if exists tr_payable_ai;

create table if not exists payable_audit(
    audit_datetime datetime, 
    aduit_user varchar(50),
    changes varchar(500));

delimiter//

create trigger tr_payable_ai
after insert on payable
for each row

begin
  insert into payable_audit values(
       now(),
       user(),
       concat('changes for row payable_id: ', new.payable_id,
              ' company: ', new_company,
              ' amount: ',new.amount,
              ' service: ',new.service
              ));
   end //
  delimiter ;
  ```
      



**--After Delete triggers--**  
  

```sql
use triggers_database;
drop trigger if exists tr_payable_ad;

--create trigger after delete
delimiter //
create trigger tr_payable_ad
after delete on payable
for each row
begin 
 insert into payable_audit values(now(), user(), 
 concat('Delete row for payable_id ', old.payable_id,' ',
        'Company: ',old.company,' ',
        'amount: ', old.amount,' ',
        'Service: ', old.service)
 );
 end //
 delimiter ;
 
 -- delete from table
 delete from payable where service = 'Usage fee';
 -- audit the table after delete 
 select * from payable_audit ;
 ```
 
 
 show triggers; -- list all triggers in current database
 show tables; -- list all tables in current database
 
 **--After Update triggers--**  
 
 ```sql
 --create trigger after update
 drop trigger if exists tr_payable_au
 
 delimiter //
 
 create trigger tr_payable_au
 after update on payable
 for each row
 
 begin
   set @change_msg = concat('updated row for payable_id ', old.payable_id);
   if (old.company != new.company) then
   set @change_msg = concat(@change_msg,' . comapny changed from  ' , old.company, ' to ' , new.company);
   end if;
   
   if (old.amount != new.amount) then
   set @change_msg = concat(@change_msg,' . amount changed from  ' , old.amount, ' to ' , new.amount);
   end if;
   
   if (old.service != new.service) then
   set @change_msg = concat(@change_msg,' . service changed from  ' , old.service, ' to ' , new.service);
   end if;
   
   insert into payable_audit values(now(), user(), @change_msg);
   
   end //
   delimiter ;
  -- -----------------------------------------------------------
   set sql_safe_updates = 0;
   
   update payable set amount = 100000, company = 'House of Larry' where payable_id = 3;
   select * from payable_audit;
  
   set sql_safe_updates=1;
   ```

### 2. Triggers That Affect Data.


**--Before Insert Triggers--**
```sql

create database bank;
use bank;
create table if not exists credit(customer_id int, customer_name varchar(100), credit_score int);
drop trigger if exists tr_credit_bi;

delimiter // 
create trigger tr_credit_bi
before insert on credit
for each row

begin 
  if (new.credit_score <300) then
   set new.credit_score  = 300;
end if;
 
 if (new.credit_score > 850) then
  set new.credit_score = 850;
end if;

end //
delimiter ;

insert into credit values(1,'Milnor John', 980),(2,'Patty Po',145),(3,'Vinny Middle-class',702);
select * from credit;

-- ---------------------------------------
```


**--Before Update Triggers--**
```sql

drop trigger if exists tr_credit_bu

delimiter //

create trigger tr_credit_bu
before update on credit
for each row

begin 
  if (new.credit_score <300) then
   set new.credit_score  = 300;
end if;
 
 if (new.credit_score > 850) then
  set new.credit_score = 850;
end if;

end //
delimiter ;

update credit set credit_score = 1111
where customer_id = 3;
  
-- ------------------------------------------
  
delimiter //
create trigger tr_newcredit_bu
before update on credit
for each row
begin
  if (new.credit_score < old.credit_score) then
     set new.credit_score = old.credit_score;
  end if;
end //
update credit set credit_score = 500
where customer_id = 2;

-- ---------------------------------------------
```

**--Before Delete Triggers--**
```sql

drop trigger if exists tr_credit_bd


delimiter //

create trigger tr_credit_bd
before delete on credit
for each row
begin
  if (old.credit_score >750) then
    signal sqlstate '45000'
    set message_text = 'Cannot delete scores over 750';
  end if;
end //
delimiter ;

-- --------------------------------------------------
```
**--Other Cases for before Delete Triggers--**


In MySQL, in a `BEFORE DELETE` trigger, you can use several statements to manage or manipulate the data or conditions before the delete operation. Besides the `SIGNAL` statement, here are some of the frequently used statements you can include in a `BEFORE DELETE` trigger:

1. **Conditional Logic (IF-THEN-ELSE)**: As you’ve used in your trigger, you can include more complex conditional logic.
   ```sql
   IF (condition) THEN
      -- logic
   ELSE
      -- alternative logic
   END IF;
   ```

2. **SET Statement**: Used to assign values to variables, either local variables or session variables.
   ```sql
   SET @variable_name = value;
   ```

3. **SELECT INTO Statement**: Used to fetch values into variables from another table or a query.
   ```sql
   SELECT column_name INTO @variable FROM another_table WHERE condition;
   ```

4. **INSERT Statement**: You can insert a record into another table, such as a log or archive table.
   ```sql
   INSERT INTO archive_table (column1, column2) VALUES (OLD.column1, OLD.column2);
   ```

5. **UPDATE Statement**: You can update records in another table based on certain conditions.
   ```sql
   UPDATE another_table SET column_name = value WHERE condition;
   ```

6. **CALL Statement (for Stored Procedures)**: You can call a stored procedure from within the trigger.
   ```sql
   CALL stored_procedure_name(parameters);
   ```

7. **SIGNAL**: Used to raise an error condition (as in your example).
   ```sql
   SIGNAL SQLSTATE '45000'
   SET MESSAGE_TEXT = 'Error message';
   ```

8. **LEAVE**: Exit from a block, similar to `break` in other languages. Useful inside loops or conditional blocks.
   ```sql
   LEAVE block_label;
   ```

9. **DECLARE**: Used to declare local variables inside the trigger.
   ```sql
   DECLARE variable_name datatype;
   ```

10. **HANDLER Statement**: This is used for exception handling within the trigger.
   ```sql
   DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
   BEGIN
      -- handle exception
   END;
   ```

### Example Incorporating Multiple Statements
Here’s an extended version of your trigger that includes multiple commonly used statements:

```sql
DELIMITER //
CREATE TRIGGER tr_credit_bd
BEFORE DELETE ON credit
FOR EACH ROW
BEGIN
   DECLARE account_status VARCHAR(20);
   -- Example of conditional logic
   IF (OLD.credit_score > 750) THEN
     -- Example of SIGNAL
     SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'Cannot delete scores over 750';
   ELSE
     -- Example of SELECT INTO
     SELECT status INTO account_status FROM accounts WHERE account_id = OLD.account_id;
     
     -- Example of conditional logic based on fetched data
     IF (account_status = 'Active') THEN
       -- Example of an update to another table
       UPDATE accounts SET status = 'Pending' WHERE account_id = OLD.account_id;
     END IF;
     
     -- Example of inserting into another table (logging or archiving)
     INSERT INTO audit_log (operation, credit_id, old_score, log_time)
     VALUES ('DELETE', OLD.credit_id, OLD.credit_score, NOW());
   END IF;
END //
DELIMITER ;
```

This example demonstrates the use of `IF-THEN`, `SELECT INTO`, `INSERT`, `UPDATE`, and `SIGNAL`, which are frequently used in triggers, along with other statements that could be used depending on the logic needed for the trigger.

## E. Remarks

The general usage patterns for `AFTER` and `BEFORE` triggers in MySQL are typically as follows:

### `AFTER` Triggers:
- **`AFTER INSERT`, `AFTER UPDATE`, or `AFTER DELETE`** are generally used when you want to **audit data** or **perform some action** after the data has already been modified in the database. Since the changes have already occurred, these triggers can be useful for logging changes, updating related records, maintaining historical tables, or notifying other systems.

### `BEFORE` Triggers:
- **`BEFORE INSERT`, `BEFORE UPDATE`, or `BEFORE DELETE`** are used when you want to **affect the data before it is committed to the database**. These triggers are useful when you need to enforce business rules, modify values, or perform validations before the actual insert, update, or delete happens.

### Example Scenarios:

1. **`AFTER` Triggers for Auditing:**
   - If you want to track changes made to a table, an `AFTER UPDATE` or `AFTER DELETE` trigger can log the previous values to an audit table after the changes have been made.

   ```sql
   CREATE TRIGGER after_employee_update
   AFTER UPDATE ON employees
   FOR EACH ROW
   BEGIN
       INSERT INTO employee_audit (employee_id, old_salary, new_salary, updated_at)
       VALUES (OLD.id, OLD.salary, NEW.salary, NOW());
   END;
   ```

2. **`BEFORE` Triggers for Data Validation/Modification:**
   - If you want to ensure that no employee's salary is set below a certain minimum value before an update or insert, you can use a `BEFORE INSERT` or `BEFORE UPDATE` trigger to adjust or reject the data.

   ```sql
   CREATE TRIGGER before_employee_insert
   BEFORE INSERT ON employees
   FOR EACH ROW
   BEGIN
       IF NEW.salary < 3000 THEN
           SET NEW.salary = 3000; -- Set minimum salary if lower
       END IF;
   END;
   ```

### Summary:
- **`AFTER` triggers** are typically used for **auditing** or **actions based on changes** that have already occurred.
- **`BEFORE` triggers** are used to **validate, modify, or affect data** before it is committed to the database.

```sql
-- -------------------------------------------------------------------------------------------------------

```

Once triggers are created on a given table, they will automatically fire whenever the corresponding action (such as `INSERT`, `UPDATE`, or `DELETE`) is executed on the table. These triggers are associated with specific events (before or after an insert, update, or delete) and will be triggered every time the event occurs.

### Key Points to Remember:
1. **`BEFORE` triggers** will fire **before** the specified action is completed (e.g., before inserting a row).
2. **`AFTER` triggers** will fire **after** the specified action is completed (e.g., after updating a row).
3. Triggers are associated with a specific table, so any action taken on that table that matches the trigger event will cause the trigger to execute.

For example:
- If you create a `BEFORE INSERT` trigger on a table, it will fire every time an `INSERT` operation is performed on that table.
- If you create an `AFTER UPDATE` trigger on a table, it will fire every time an `UPDATE` operation is performed on that table.
- Similarly, a `BEFORE DELETE` trigger will fire before a `DELETE` operation is executed on that table.

### Example of Trigger Creation:

```sql
CREATE TRIGGER before_insert_employee
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
    -- Trigger logic here
    SET NEW.salary = IF(NEW.salary < 3000, 3000, NEW.salary); -- Ensure minimum salary
END;
```

In this example, the `BEFORE INSERT` trigger will fire before any new row is inserted into the `employees` table, allowing you to modify or validate data before the insert happens.

**To show all triggers in MySQL when**

**1.**  you don't know which database is currently in use, you can query the `information_schema` database, which contains metadata about all databases, including triggers. Here's the query you can use:

```sql
SELECT TRIGGER_SCHEMA, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, ACTION_STATEMENT
FROM information_schema.TRIGGERS;
```

### Explanation:
- **TRIGGER_SCHEMA**: The name of the database where the trigger is defined.
- **TRIGGER_NAME**: The name of the trigger.
- **EVENT_MANIPULATION**: The type of event that activates the trigger (e.g., `INSERT`, `UPDATE`, `DELETE`).
- **EVENT_OBJECT_TABLE**: The table that the trigger is associated with.
- **ACTION_STATEMENT**: The SQL statement that is executed when the trigger is activated.

This query will give you a list of all triggers across all databases in your MySQL instance, so you can see which triggers exist without needing to specify a particular database first.

**2.**  You know which database is currently in use

```sql
 show triggers If you know which database you're using and want to display all the triggers for that specific database in MySQL, you can either query the `information_schema.TRIGGERS` table or use a specific MySQL command while connected to the database.

### Option 1: Using `SHOW TRIGGERS` command
Once you are connected to the desired database, you can simply run:

```sql
SHOW TRIGGERS;
```

This will list all triggers for the currently selected database.

### Option 2: Querying `information_schema`
Alternatively, you can query the `information_schema.TRIGGERS` table but filter for the specific database. Replace `your_database_name` with the actual database name:

```sql
SELECT TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, ACTION_STATEMENT
FROM information_schema.TRIGGERS
WHERE TRIGGER_SCHEMA = 'your_database_name';
```

This query will return all triggers for the specified database.